env:
  TERM: xterm-256color
  EDITOR: /usr/bin/nvim
window:
  decorations: none # full|none
  opacity: 1
  startup-mode: Maximized
  gtk_theme_variant: dark
scrolling:
  history: 2000
live_config_reload: true
working_directory: None
font:
  normal:
    family: Fira Code Nerd Font Mono
  size: 12.0
colors:
  # Default colors
  primary:
    background: '0x1e1e1e'
    foreground: '0xd6d6d6'

    dim_foreground:    '0xdbdbdb'
    bright_foreground: '0xd9d9d9'
    dim_background:    '0x202020' # not sure
    bright_background: '0x3a3a3a' # not sure

  # Cursor colors
  cursor:
    text:   '0x2c2c2c'
    cursor: '0xd9d9d9'

  # Normal colors
  normal:
    black:   '0x1c1c1c'
    red:     '0xbc5653'
    green:   '0x909d63'
    yellow:  '0xebc17a'
    blue:    '0x7eaac7'
    magenta: '0xaa6292'
    cyan:    '0x86d3ce'
    white:   '0xcacaca'

  # Bright colors
  bright:
    black:   '0x636363'
    red:     '0xbc5653'
    green:   '0x909d63'
    yellow:  '0xebc17a'
    blue:    '0x7eaac7'
    magenta: '0xaa6292'
    cyan:    '0x86d3ce'
    white:   '0xf7f7f7'

  # Dim colors
  dim:
    black:   '0x232323'
    red:     '0x74423f'
    green:   '0x5e6547'
    yellow:  '0x8b7653'
    blue:    '0x556b79'
    magenta: '0x6e4962'
    cyan:    '0x5c8482'
    white:   '0x828282'
key_bindings:
  - { key: V,              mods: Control|Shift,           action: Paste            }
  - { key: C,              mods: Control|Shift,           action: Copy             }
  - { key: Plus,           mods: Control,                 action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                 action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                 action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                 action: DecreaseFontSize }
  - { key: Key0,           mods: Control,                 action: ResetFontSize    }

