export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export CODEEDITOR="/usr/bin/vim"
[[ -f /usr/bin/firefox ]] && export BROWSER="/usr/bin/firefox"

alias ls="/usr/bin/exa"
alias ll="/usr/bin/exa -l"
alias lla="/usr/bin/exa -la"
[[ -f $(command -v batcat) ]] && [[ ! -f $(command -v bat) ]] && alias bat="/usr/bin/batcat"
[[ -f $(command -v fdfind) ]] && [[ ! -f $(command -v fd) ]] && alias fd="/usr/bin/fdfind"
