#!/bin/sh

# variable initiated in /etc/profile.d
WORKPLACE=$(printenv WORKPLACE)

setxkbmap -model pc105 -layout fr -variant ,azerty
numlockx on

# setup screen disposition for work
if [ "$WORKPLACE" = WORK ];
then
  xrandr --output eDP1 --mode 1920x1080 --output HDMI1 --mode 1920x1080 --left-of eDP1
elif [ "$WORKPLACE" = HOME ];
then
  echo "TODO"
  # xrandr --output eDP1 --mode 1920x1080 --output HDMI1 --mode 1920x1080 --left-of eDP1
fi;

exec dbus-launch leftwm

