import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "UbuntuMonoNerdFont", style = "Regular" }
size = 18.0

[shell]
program = "tmux"
args = ["new-session", "-A", "-D", "-s", "main", "-n", "start"]
