
[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations = "None"

[font]
normal = { family = "UbuntuMonoNerdFont", style = "Regular" }
size = 18.0

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[terminal]

[terminal.shell]
program = "zsh"
args = ["-l", "-i"]
